/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class crud extends javax.swing.JPanel {

    private javax.swing.JPanel pnlAddUser;
    DefaultTableModel model;

    /**
     * Creates new form crud
     */
    public crud() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setBackground(new java.awt.Color(251, 251, 251));
        setLayout(null);

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Password", "Jabatan"
            }
        ));
        jScrollPane1.setViewportView(tableUser);

        add(jScrollPane1);
        jScrollPane1.setBounds(26, 55, 732, 372);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(26, 6, 72, 23);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(116, 6, 72, 23);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh);
        btnRefresh.setBounds(206, 6, 72, 23);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(296, 6, 72, 23);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(386, 6, 72, 23);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        add(txtSearch);
        txtSearch.setBounds(470, 6, 288, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tableUser.getSelectedRow();
        if (row != -1) {
            int id = Integer.parseInt(tableUser.getValueAt(row, 0).toString());
            deleteUser(id);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih user yang ingin dihapus!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       String nama = JOptionPane.showInputDialog("Masukkan Nama:");
        String username = JOptionPane.showInputDialog("Masukkan Username:");
        String password = JOptionPane.showInputDialog("Masukkan Password:");
        String jabatan = JOptionPane.showInputDialog("Masukkan Jabatan (admin/kasir):");
        addUser(nama, username, password, jabatan);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tableUser.getSelectedRow();
        if (row != -1) {
            int id = Integer.parseInt(tableUser.getValueAt(row, 0).toString());
            String nama = JOptionPane.showInputDialog("Ubah Nama:", tableUser.getValueAt(row, 1));
            String username = JOptionPane.showInputDialog("Ubah Username:", tableUser.getValueAt(row, 2));
            String password = JOptionPane.showInputDialog("Ubah Password:", tableUser.getValueAt(row, 3));
            String jabatan = JOptionPane.showInputDialog("Ubah Jabatan (admin/kasir):", tableUser.getValueAt(row, 4));
            updateUser(id, nama, username, password, jabatan);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih user yang ingin diupdate!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtSearch.getText();
        searchUser(keyword);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUser;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    public void loadTable() {
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Jabatan");

        try {
            Connection c = koneksi.getConnection();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery("SELECT * FROM user");

            while (r.next()) {
                model.addRow(new Object[]{
                    r.getInt("id"),
                    r.getString("nama"),
                    r.getString("username"),
                    r.getString("password"),
                    r.getString("jabatan")
                });
            }
            tableUser.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    // 🔹 Tambah Data
    private void addUser(String nama, String username, String password, String jabatan) {
        try {
            Connection c = koneksi.getConnection();
            String sql = "INSERT INTO user (nama, username, password, jabatan) VALUES (?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nama);
            p.setString(2, username);
            p.setString(3, password);
            p.setString(4, jabatan);
            p.executeUpdate();
            JOptionPane.showMessageDialog(this, "User berhasil ditambahkan!");
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menambah user: " + e.getMessage());
        }
    }

    // 🔹 Update Data
    private void updateUser(int id, String nama, String username, String password, String jabatan) {
        try {
            Connection c = koneksi.getConnection();
            String sql = "UPDATE user SET nama=?, username=?, password=?, jabatan=? WHERE id=?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nama);
            p.setString(2, username);
            p.setString(3, password);
            p.setString(4, jabatan);
            p.setInt(5, id);
            p.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data user berhasil diupdate!");
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal update: " + e.getMessage());
        }
    }

    // 🔹 Hapus Data
    private void deleteUser(int id) {
        try {
            Connection c = koneksi.getConnection();
            String sql = "DELETE FROM user WHERE id=?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setInt(1, id);
            p.executeUpdate();
            JOptionPane.showMessageDialog(this, "User berhasil dihapus!");
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal hapus: " + e.getMessage());
        }
    }

    // 🔹 Pencarian Data
    private void searchUser(String keyword) {
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Username");
        model.addColumn("Password");
        model.addColumn("Jabatan");

        try {
            Connection c = koneksi.getConnection();
            String sql = "SELECT * FROM user WHERE nama LIKE ? OR username LIKE ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, "%" + keyword + "%");
            p.setString(2, "%" + keyword + "%");
            ResultSet r = p.executeQuery();

            while (r.next()) {
                model.addRow(new Object[]{
                    r.getInt("id"),
                    r.getString("nama"),
                    r.getString("username"),
                    r.getString("password"),
                    r.getString("jabatan")
                });
            }
            tableUser.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mencari: " + e.getMessage());
        }
    }

}
