/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class ProductManage extends javax.swing.JPanel {

    DefaultTableModel model;

    public ProductManage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();

        setLayout(null);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(20, 20, 72, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(110, 20, 72, 23);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(200, 20, 72, 23);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(290, 20, 72, 23);
        add(txtCari);
        txtCari.setBounds(380, 20, 280, 22);

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelProduk);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 730, 340);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String nama = JOptionPane.showInputDialog("Masukkan Nama Produk:");
            String jenis = JOptionPane.showInputDialog("Masukkan Jenis Produk:");
            String hargaStr = JOptionPane.showInputDialog("Masukkan Harga Produk:");
            String satuan = JOptionPane.showInputDialog("Masukkan Satuan:");
            String keterangan = JOptionPane.showInputDialog("Masukkan Keterangan:");

            // validasi input kosong
            if (nama == null || jenis == null || hargaStr == null || satuan == null || keterangan == null) {
                JOptionPane.showMessageDialog(this, "Input dibatalkan!");
                return;
            }

            // ubah string ke double
            double harga;
            try {
                harga = Double.parseDouble(hargaStr);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Harga harus berupa angka!");
                return;
            }

            // panggil method tambah produk
            addProduct(nama, jenis, harga, satuan, keterangan);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tabelProduk.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih produk yang ingin dihapus!");
        return;
    }

    // ambil id produk dari kolom pertama (sesuaikan index-nya)
    String id = tabelProduk.getValueAt(row, 0).toString();

    int confirm = JOptionPane.showConfirmDialog(this, 
        "Yakin ingin menghapus produk ini?", 
        "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            Connection c = koneksi.getConnection();
            String sql = "DELETE FROM produk WHERE id_produk = ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id);
            p.executeUpdate();

            JOptionPane.showMessageDialog(this, "Produk berhasil dihapus!");
            loadTableProduct(); // refresh data
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
     int row = tabelProduk.getSelectedRow();  // ganti sesuai nama JTable kamu
    if (row != -1) {
        // ambil id produk dari kolom pertama
        int id = Integer.parseInt(tabelProduk.getValueAt(row, 0).toString());

        // ambil nilai lama dari tabel untuk dijadikan default input
        String nama = JOptionPane.showInputDialog("Ubah Nama Produk:", tabelProduk.getValueAt(row, 1));
        String jenis = JOptionPane.showInputDialog("Ubah Jenis Produk:", tabelProduk.getValueAt(row, 2));
        String hargaStr = JOptionPane.showInputDialog("Ubah Harga:", tabelProduk.getValueAt(row, 3));
        String satuan = JOptionPane.showInputDialog("Ubah Satuan:", tabelProduk.getValueAt(row, 4));
        String keterangan = JOptionPane.showInputDialog("Ubah Keterangan:", tabelProduk.getValueAt(row, 5));

        // validasi input kosong
        if (nama == null || jenis == null || hargaStr == null || satuan == null || keterangan == null) {
            JOptionPane.showMessageDialog(this, "Update dibatalkan!");
            return;
        }

        // konversi harga dari String ke double
        double harga;
        try {
            harga = Double.parseDouble(hargaStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka!");
            return;
        }

        // panggil fungsi update
        updateProduct(id, nama, jenis, harga, satuan, keterangan);

    } else {
        JOptionPane.showMessageDialog(this, "Pilih produk yang ingin diupdate!");
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtCari.getText();

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Nama Produk");
    model.addColumn("Jenis");
    model.addColumn("Harga");
    model.addColumn("Satuan");
    model.addColumn("Keterangan");

    try {
        Connection c = koneksi.getConnection();
        String sql = "SELECT * FROM produk WHERE nama_produk LIKE ? OR jenis LIKE ?";
        PreparedStatement p = c.prepareStatement(sql);
        p.setString(1, "%" + keyword + "%");
        p.setString(2, "%" + keyword + "%");
        ResultSet r = p.executeQuery();

        while (r.next()) {
            model.addRow(new Object[]{
                r.getString("id"),
                r.getString("nama_produk"),
                r.getString("jenis"),
                r.getString("harga"),
                r.getString("satuan"),
                r.getString("keterangan")
            });
        }
        tabelProduk.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Pencarian gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelProduk;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

    public void loadTableProduct() {
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama Produk");
        model.addColumn("Jenis");
        model.addColumn("Harga");
        model.addColumn("Satuan");
        model.addColumn("Keterangan");

        try {
            Connection c = koneksi.getConnection();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery("SELECT * FROM produk");

            while (r.next()) {
                model.addRow(new Object[]{
                    r.getInt("id"),
                    r.getString("nama_produk"),
                    r.getString("jenis"),
                    r.getDouble("harga"),
                    r.getString("satuan"),
                    r.getString("keterangan")
                });
            }
            tabelProduk.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    // ==================== ADD PRODUK ====================
    private void addProduct(String nama, String jenis, double harga, String satuan, String keterangan) {
        try {
            Connection c = koneksi.getConnection();
            String sql = "INSERT INTO produk (nama_produk, jenis, harga, satuan, keterangan) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nama);
            p.setString(2, jenis);
            p.setDouble(3, harga);
            p.setString(4, satuan);
            p.setString(5, keterangan);
            p.executeUpdate();

            JOptionPane.showMessageDialog(this, "Produk berhasil ditambahkan!");
            loadTableProduct();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menambah produk: " + e.getMessage());
        }
    }

    // ==================== UPDATE PRODUK ====================
    private void updateProduct(int id, String nama, String jenis, double harga, String satuan, String keterangan) {
        try {
            Connection c = koneksi.getConnection();
            String sql = "UPDATE produk SET nama_produk=?, jenis=?, harga=?, satuan=?, keterangan=? WHERE id=?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nama);
            p.setString(2, jenis);
            p.setDouble(3, harga);
            p.setString(4, satuan);
            p.setString(5, keterangan);
            p.setInt(6, id);
            p.executeUpdate();

            JOptionPane.showMessageDialog(this, "Produk berhasil diupdate!");
            loadTableProduct();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal update produk: " + e.getMessage());
        }
    }

    // ==================== DELETE PRODUK ====================
    private void deleteProduct(int id) {
        try {
            Connection c = koneksi.getConnection();
            String sql = "DELETE FROM produk WHERE id=?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setInt(1, id);
            p.executeUpdate();

            JOptionPane.showMessageDialog(this, "Produk berhasil dihapus!");
            loadTableProduct();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal hapus produk: " + e.getMessage());
        }
    }

    // ==================== SEARCH PRODUK ====================
    private void searchProduct(String keyword) {
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama Produk");
        model.addColumn("Jenis");
        model.addColumn("Harga");
        model.addColumn("Satuan");
        model.addColumn("Keterangan");

        try {
            Connection c = koneksi.getConnection();
            String sql = "SELECT * FROM produk WHERE nama_produk LIKE ? OR jenis LIKE ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, "%" + keyword + "%");
            p.setString(2, "%" + keyword + "%");
            ResultSet r = p.executeQuery();

            while (r.next()) {
                model.addRow(new Object[]{
                    r.getInt("id"),
                    r.getString("nama_produk"),
                    r.getString("jenis"),
                    r.getDouble("harga"),
                    r.getString("satuan"),
                    r.getString("keterangan")
                });
            }
            tabelProduk.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mencari: " + e.getMessage());
        }
    }

}
