/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;

/**
 *
 * @author LENOVO
 */
public class riwayatTransaksiAdmin extends javax.swing.JPanel {

    private int idKasir;

    public riwayatTransaksiAdmin() {
        initComponents();
        idKasir = 0;
        loadKasir();

        dcTanggal.setDate(new java.util.Date()); // default hari ini

        cbKasir.addActionListener(e -> {
            if (cbKasir.getSelectedItem() != null) {
                String item = cbKasir.getSelectedItem().toString();
                idKasir = Integer.parseInt(item.split(" - ")[0]);
                loadRiwayatAdmin();
            }
        });

    }

    ;

  public void loadKasir() {
        cbKasir.removeAllItems();
        cbKasir.addItem("0 - Semua Kasir");

        try {
            Connection c = koneksi.getConnection();
            String sql = "SELECT id, nama FROM user WHERE LOWER(jabatan) = 'kasir'";
            PreparedStatement ps = c.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                cbKasir.addItem(
                        rs.getInt("id") + " - " + rs.getString("nama")
                );
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void loadRiwayatAdmin() {
        DefaultTableModel model = (DefaultTableModel) tblRiwayatAdmin.getModel();
        model.setRowCount(0);

        if (dcTanggal.getDate() == null) {
            return; // stop kalau tanggal belum dipilih
        }

        String sql
                = "SELECT u.nama AS nama_kasir, p.nama_produk, "
                + "SUM(dt.jumlah) AS total_terjual, "
                + "SUM(dt.subtotal) AS total_pendapatan "
                + "FROM transaksi t "
                + "JOIN detail_transaksi dt ON t.no_transaksi = dt.no_transaksi "
                + "JOIN produk p ON dt.id_produk = p.id "
                + "JOIN user u ON t.id_user = u.id "
                + "WHERE (? = 0 OR t.id_user = ?) "
                + "AND DATE(t.tanggal) = ? "
                + "GROUP BY u.nama, p.nama_produk";

        try {
            PreparedStatement ps = koneksi.getConnection().prepareStatement(sql);

            ps.setInt(1, idKasir);
            ps.setInt(2, idKasir);
            ps.setDate(3, new java.sql.Date(dcTanggal.getDate().getTime()));

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nama_kasir"),
                    rs.getString("nama_produk"),
                    rs.getInt("total_terjual"),
                    rs.getInt("total_pendapatan")
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

        loadTotalAdmin();
    }

    public void loadTotalAdmin() {
        if (dcTanggal.getDate() == null) {
            lblTotalTransaksi.setText("0");
            lblTotalPendapatan.setText("Rp 0");
            return;
        }

        String sql
                = "SELECT COUNT(DISTINCT t.no_transaksi) AS total_transaksi, "
                + "SUM(dt.subtotal) AS total_pendapatan "
                + "FROM transaksi t "
                + "JOIN detail_transaksi dt ON t.no_transaksi = dt.no_transaksi "
                + "WHERE (? = 0 OR t.id_user = ?) "
                + "AND DATE(t.tanggal) = ?";

        try {
            PreparedStatement ps = koneksi.getConnection().prepareStatement(sql);
            ps.setInt(1, idKasir);
            ps.setInt(2, idKasir);
            ps.setDate(3, new java.sql.Date(dcTanggal.getDate().getTime()));

            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                lblTotalTransaksi.setText(rs.getString("total_transaksi"));
                lblTotalPendapatan.setText("Rp " + rs.getInt("total_pendapatan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dcTanggal = new com.toedter.calendar.JDateChooser();
        cbKasir = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRiwayatAdmin = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalTransaksi = new javax.swing.JLabel();
        lblTotalPendapatan = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);
        add(dcTanggal);
        dcTanggal.setBounds(610, 30, 88, 22);

        cbKasir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbKasir);
        cbKasir.setBounds(210, 30, 72, 22);

        tblRiwayatAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Kasir", "Nama Produk", "Jumlah penjualan", "Jumlah Pendapatan"
            }
        ));
        jScrollPane1.setViewportView(tblRiwayatAdmin);

        add(jScrollPane1);
        jScrollPane1.setBounds(70, 90, 780, 320);

        jLabel1.setText("Total Transaksi  :");
        add(jLabel1);
        jLabel1.setBounds(70, 420, 100, 16);

        jLabel2.setText("Total Pendapatan : ");
        add(jLabel2);
        jLabel2.setBounds(70, 440, 110, 16);

        lblTotalTransaksi.setText("jLabel3");
        add(lblTotalTransaksi);
        lblTotalTransaksi.setBounds(190, 420, 37, 16);

        lblTotalPendapatan.setText("jLabel4");
        add(lblTotalPendapatan);
        lblTotalPendapatan.setBounds(190, 440, 160, 16);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbKasir;
    private com.toedter.calendar.JDateChooser dcTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalPendapatan;
    private javax.swing.JLabel lblTotalTransaksi;
    private javax.swing.JTable tblRiwayatAdmin;
    // End of variables declaration//GEN-END:variables
}
